version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: gscuio.tb705385ieke54f3
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEFXVVNpTDlRaE1aa1VKOE9CdDZraitNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5qQTNNamd3TURRNE5EaGFGdzB6TmpBM01qVXdNRFE0TkRoYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBaEQxeEtUWG15cnZESTBmZUJ3ekYzSW52d2M4UVlBYTdXbFlVCmdiZHp2M1NqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVWFlHeWpkbUh4aTNhUWlPbwpHdXhRcnB2L2xPUXdCUVlESzJWd0EwRUE3NjdGN29NMHJrdzhKRk1pcXEzWVlSUTJBQm5scWcxc3gxc3lsM0NQCngzYjNFSjZMYWVmTmJSR2wzNzdpTEZGSzJmME4rMWpXd1gvNlRuVkFLaXZ5Q0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJTGNkWkNQTlI5VU9Lb1VQUU1udk84V2c5OWRJL2xZVzErS2JPdHZVN21mbQotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.36.2
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network:
        interfaces:
            - interface: ens18
              addresses:
                - 192.168.1.201/24
              routes:
                - network: 0.0.0.0/0
                  gateway: 192.168.1.1
              dhcp: false
        nameservers:
            - 192.168.1.1
    install:
        disk: /dev/sda
        image: ghcr.io/siderolabs/installer:v1.13.6
        wipe: false
        grubUseUKICmdline: true
    features:
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
    id: ascXMTZp4sIm1S14OkLiuFChYN0MxgEUVX6v6GdCbng=
    secret: 2HlV9LJn4aSCzc9IfUL19IxdXqtBO+g6aBEXIrntYjU=
    controlPlane:
        endpoint: https://192.168.1.201:6443
    clusterName: hellnet
    network:
        cni:
            name: none
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: q7oq6y.d2048kopxmp3mfu8
    secretboxEncryptionSecret: B4jcvPjF99XM4CewgVUu/Q7uqYGx4HQu18Ym3kFY5hA=
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVRDZ0F3SUJBZ0lSQVBKZCszVlppeGg0RExDd0NkUFE5bWN3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakEzTWpnd01EUTRORGhhRncwek5qQTNNalV3TURRNApORGhhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRGdi9xczNPS0VPUWZKVlBOT2czaDFJbjI5OE92RDB3SWo5ZWpzNFFmcFQ2NXJqTFk3Ykt4Q0hxencKMlNveE8waVRhMTYxMFRqdTZQU3c1cEFLVFBJVW8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGTEZXU0Yxc1grb3EzVTJTdzFTOUNJcWNSb1MwTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUUvSFQ2a0oKQlc4YXBMWXhydExoQzY0cUo0Y3Z6VURBUzNOeUhLL0ZTcno2QWlCL28vNjlLUUJmODZ2R1hVVTlyWVJSYVFnRwo0Szg0dTR3UjNvc1FOb05Cdnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUJ5c3lyZFF4N044TzYrNmFzQVYwa1ZUaEZSSmRnaENNZlFsZTFtUFU5eCtvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFeGIvNnJOemloRGtIeVZUelRvTjRkU0o5dmZEcnc5TUNJL1hvN09FSDZVK3VhNHkyTzJ5cwpRaDZzOE5rcU1UdElrMnRldGRFNDd1ajBzT2FRQ2t6eUZBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYekNDQVFhZ0F3SUJBZ0lSQUwxYmtxS2tLVzJvTjBIeDQ2dWllT1F3Q2dZSUtvWkl6ajBFQXdJd0FEQWUKRncweU5qQTNNamd3TURRNE5EaGFGdzB6TmpBM01qVXdNRFE0TkRoYU1BQXdXVEFUQmdjcWhrak9QUUlCQmdncQpoa2pPUFFNQkJ3TkNBQVRienE5N3JyREJkRWhNL0Y3MXF6QWswL2Nwcytma0trTHF1UWxJK0h6UHptUU13THllCkFCOFYxSDMzM0d4Y3hUaEw0bC9qMFlCbmtzVVRGNkw1Yk5TWW8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXcKSFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpIUVlEVlIwT0JCWUVGRmNESythYkxBcGpTa09mWjlsa0s4WGRReWloTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDCklIZHJtMkZnc3VEZTA2UE9sRW9tMjdNZ0hFNk5EVzBHbThEVGlhaEJxdHhwQWlBZXdYZERQVWxNU0dtK2ROWEIKMldaSC9NaFZNU3RBa0tlMG11elFsOWYyVWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUVNZGdnZDg3QmJYVkJ4ZUtubHFZQmdnUkVQa2k3WFAwb09uOGJvcjU5V2RvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMjg2dmU2Nnd3WFJJVFB4ZTlhc3dKTlAzS2JQbjVDcEM2cmtKU1BoOHo4NWtETUM4bmdBZgpGZFI5OTl4c1hNVTRTK0pmNDlHQVo1TEZFeGVpK1d6VW1BPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBOUU2NmRkcW9VVXcrTXg3MUNoQWRSZlVJaFhPeGJUaGtVRXVTM2NwaWlnNWhBaXdqCk9DU3M1T0JxamlubVIya1F4bHFheUtyMXRON2dzYUpQVjJrSkVsOURmeklBbDU1RWdPSkxJZGNlWG03bjdMcnUKZlpTVzJ3ZFVrZndIcy94WUhZS2F6RDdPV3pWcTllbkp0UzdjeFp6Rm5HTHhXaWR4cWFab3pNK1c4M2EzSnZNSApuNGRDeGpTN2cwL2poelJuUWNlSlNXQkpXQnA2Zko5dm5WZFZYWkZBT0NkK3B6dExyNDlVN3FjbkpMeWY0NjkyCnorL0N1cDZ0STZZdFRvanRiOXZPTTE1Uk8zSlVNRXpkUlRHRnk3VFdPRXhvTXArVkxCR3hlS25jM3VZWldYUjkKSExpcTY2SVl5MXNQdkV2eVVaZ1g0K3RickxWeXBuQzhzbGcxS2NFVzh5VkhzOEluUk9nYW0zdlkzSXpnRDdnego3elVUa3NwZzI0enllN0JNNmhUNitHcUlDcDFRV2gvTzdjRE5jRFZlUzZ3RUxuWkFTYUZIU25iMUhRNEJscnhFCnJNU2lBOUJmNTZtRlJxZmRTcmptMnpQdHovQkVsMzA0b3BNZzdMaEtBdHdZMlBFWmtuUzJVNEZWK0tmODZ1WisKbjQxTzZxL0g0TG5XS01LUFhkSVRHRTNYS3EyQ3ROd3JQTlBPOVFrWmJiOU16cFZlSzRLeERLbnVWUVVpMStxUgp4cGxqNHEraWp6WkV3ZE9KejJrelQyaGk2K1d0am1kY2dFa3E2aFRLZ1NGeTkreHMyS3V4RTFCOWVBdTB0ZVR4CjRBQWlqWHhvRVZuRm1tVGJ4Zm8zMXRUN1ppSW1rck1CY1huUXBXQlZiTG5hemtJVUxSUzM0Z1JMOHVzQ0F3RUEKQVFLQ0FnQVZ1eWtIMGE3V0tHK0I4WmQvVVNhaGNlWFRwUkpic2ovdUNvTGlXcDNBUlA0cENNOExMK3YzSWVVbwpoeDZXTElqUzgvMC9xMEZXMk5wb3dwVEhKQzhyNUxCbTBJWlA5a0tHcWxwZmhMaU5VdFVyY0FkRndXRlgwME9aCkJxK1N1WGdIQy9hRUEzUXNsY2hSWG4zVU1YcHUwMzZhWmd5czVjUk5BR0hqRWZZTjZ2bm9xNFo2a0xnR1ZHdDMKaHpRb2N5ZGFLUXNUclU1bzJWWWEzcjI1WTZyU3UxaFlobDdVTmtpSnNiaXV6OHlDRG9zMFlBZTBBRkkwY21mWgpPMjlkUkgzR1RPbC9GVDBwaWdabUUzZzlMdVlGVkMwWDdlZjQxTXdha3VwVDN0d29NWlNBcWdWMCtCSXdDb2VsCkV4RUh3VU9wTVZ1eXFOMUxOQXFpTm5YNmNURXRQS05JZ2tLV0FtNmE2cm5Na3I4M1RXazJsUHVhVVlyaThvN2IKQlpGOFI2VHFUby9kR0d5MVNEZk9VRDJ4d2pOWmdMa3ZyUG1DTWRZUW9Kc3lqNWQwZGtVbDk3VTFGb1NIaGl3QgoxU25NK2FvVCtmV3RDMzhaNkdweXM1bnc3ekRTd3pXZ2pYdHlOM1g4L2VEMDUzcXpGb3kxMThWdWhrL1UyQlF2CmJLQkR5MDBsS25scGlnUWFxWWpNK2F0cHdVc3dsWXhKZmZBb2c5ZXFmcnFPSEx3Y216UWJJckoxcnROaFlDNm0Ka3Q3Q2VSYmVvVXU0K1YxNzJMNTEybHRLMG5rNWhpdUlrcHd1U3U0elgrQUxyME14ZWpRWVFXc2t3L0VFc081bwp2eks5ZnRkRlM0dVN6U1V2OFVtbDQveGFzaE5OZUFBbjZXM2hwbXdtRkdqVWF1YTY5UUtDQVFFQStGTWEzRWY0CnN2SjRuYUNnaUdiMVZpc1dGcTgzV3RabEsrTWRrQWI4Y28wMEFqM0U4dU5qMnJYZFQ3RnZZcDAwSythbzNkbmwKLzJEMjB1cEZXa0lxb0oxMDFFbnJnZGJYTU9CMVdrcE8wS0lHTGlyVktiRW9mK2FPbVJYWlYzRzRqSW96NTk3KwpWaEx5aHdGNE1lWjlEWUo3Y1pUSW5Rb3NZOUNlRERZaTc5aE5Dai9BQmlXOHExU09MZDVHcmxnM2xSbnk4VkZ0CnZSZW9WSVM1U295eDlUTi9FZXVMQlIzSWVRT0VEeXRvZE9Bc1ZaTGhGUmFUVWM4TXhQdnNIMHFGR0svWlVGRVkKTGFmSFE1TUxJTVRjc3JQcVNvNlJHNmcvL2VOUmJMdkdoaWZXRWYrYTE0eDA1Q0JnQ3VSdmh1Ykc1UWdUSnZ1MAovMTcxWEcvNk8zZFJMd0tDQVFFQSs5dldkZmFiU1ZKNERGbU81YW8rVUF1Q1ZCRWt6RlM5SW1XeUJrdWNXZExjCk1Tb1VqNUF6T1dOMkVldTlDZU8vbEhMYWpEM0dFUnhqWmZiU3k1YU55WVRoM1BNRFVneCswb0RVWXB6ZW5RVTUKaElrcm1mRGlOOFNNVTBjRGx2NVJaUVRKWk4zdWx6MS9nT053QjZGdXhQbDJoeHFkbm96Qm8yQmtUWmo2Vzhadgo1Ty8vbnFNOHk5RFBiSVdCUEpaWGlmWCtEaTJ2TzNoelQxT1NBUVZtd1BIOUx1cFQyZmFtNzFNbDM3T0VvZHZkCm00YmNYeGRVOGRVMjFYY3FPdDZTZG9OeWJyVm94cFk5M2V2eDNVRkNLV1dENDlibnU4R29keWlRc090L0FGK28KdXN1NmFSR0lQbDhkOTVEajVIYzZaMHNvYzVkbmwwQ1VtTHR6eGlVekJRS0NBUUFPMzBOTGtBL24vN2VUa1N3cwpIeVp3VzdJOTk0NTBKVVQzNU9rL1YvdkVqSXBoMi9zd3BNZTFNSkVwbGJIYkVSa3Z5K2V2S2I2cGxkQVNmNjlaCm9YN1dFYmdPZ3NMVkN0M21jbnIweG1DRUJFQWtnYkkwaGdTcjdFMzhBeC82S2Job3lsb2pkK3A1a3pidE9QeE8KMk1RQ2pCOENoV3VpWkJxV2U4Y0xhaTZiZUxQY2VrYncxMCsrWHhrSXpEZ2xkdWtWUi9HUjNGT2JNSkNIUjArbApsRm1RR3Q1d1gwLzdKWFo5TU9XMjF0MnhxajlkZktkNFVOclAybnVrVElZdXRaTFZFS3NPTVYwbVZ0Y0xTQUl4Cm16aXdoeS92K1N2ZG9Tejc4cUpNeGM0MCtLdk1kaWQ2NDFHWTNBdUVlM3ZtYzJuVUM3REI4Kzg2SUNESHdYa1cKR0taSEFvSUJBUUNuRGlSc1RreW1EOHVNOVlKeEY4RUpPdmtSWmVXd21xeHhPbDhoQ2RvRlFuWEhMcEJBd1hjWQpvNzVYR0xSazhPbk1QM3B5OXk1L2Z3TDNTUVo4LzduQVp5R2hlcGREUHdLSUFlZmVHUXNYdjdWdEVjY1g3czArCkRHSy9naVVCYkdMMHpINEJKNnZ3S1Z4L1UxeWwweEEwR3Z2aGxXZmpHSjRBRGhtNTFyU0pWMUEwM0hRQzkyZUcKRVZUa09KR0diSHBZQ2hDZnV2RzJVcWk1ZjBjaTRrQkx6cmNPL1dMcytrdTBCc1RpWXFLZzhjTkdPK2ZFTXllbQoyTFBzVjRSdFUrQjJONjRaZkw2b3FsTVM5a09SYkkzRUE0KzkrbmZ1OC84WU9wSHVwK1d2aThQUlV2eXNZSEtzClhFNzJQT2JNVGNFeGJvckFVVGJtL25FUjlaUlBZN0U1QW9JQkFRRHNBOU51TE52WlkrR3N0TGJkempDTXRDOUEKYTJNRDJ5aXY0bENVd0dTaUlGLzJTVGx2am5kNmJFeVg1NVBBNzhiSWpPYmZraE9vUVRJcmJpL3k3NXJlck0zeApTZU0vUGUxRFhnVzErclUwVEJQaUx1cHJkWUliVk5rQ0hXN2hSNGVyMzBkKytPQk5LRk9xU0NwMitiQ2srRmRKCk9nTTZCUTNiUFplN2RHNTdPNWY1ZlRTZnhyaXg1R2xQMDI2eFRmS2x1dFVvQVFaYXJ2cE5MbVdkM2tsdmVJZ3cKVGlWbHc1R001K1cxR2dLaVJwa1lkb2xJbXk3dk9qRzBVV2tzR2FSYTlIMGdyemxPTkNxeXUvVDdDVmk4Y2dEZQoxdVpyVC9YZjR5dVdGMjJsSEpTTmZ6bUg4YSs5Z2ZRa1pEUkg5ZXNhZE83VTg4YWpGZ201T1h4MDdYSFcKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.36.2
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.36.2
    proxy:
        image: registry.k8s.io/kube-proxy:v1.36.2
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.36.2
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmakNDQVNPZ0F3SUJBZ0lRY1RjWnBkeHgwYlVTUDQvZTBmSlpEekFLQmdncWhrak9QUVFEQWpBUE1RMHcKQ3dZRFZRUUtFd1JsZEdOa01CNFhEVEkyTURjeU9EQXdORGcwT0ZvWERUTTJNRGN5TlRBd05EZzBPRm93RHpFTgpNQXNHQTFVRUNoTUVaWFJqWkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkVONS9xdXlZdjVtCkVVbHBpaFlpcHpKSWZZV0xPTkxRczd0dzZNejNxaVlVL0FjNnJGaXZTb1UrOGQyRGxVOTBBOTh4VTZ6U1pSNFgKR0p1cTJxKzhWMStqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjRApBUVlJS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVUnorU2doMTF4dklzCktiOTlwSTgxNFhyYS9VNHdDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBS29tNXQyQjlKb2hJaE5GbTNaYnd3SGUKVVBUZDdpK1lvaDFTWEw1SnVMMlNBaUVBbDdOeVpvTVhPSHM0ZkdRNXVkUjVtalprMGtheFgxemxTUVpuSlFoNApiVFk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZpMms2cE5YLy9SUEZ4ellkSUJWbm1za2VsdjVVMUdveW9makorTUZQVVBvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUTNuK3E3SmkvbVlSU1dtS0ZpS25Na2g5aFlzNDB0Q3p1M0RvelBlcUpoVDhCenFzV0s5SwpoVDd4M1lPVlQzUUQzekZUck5KbEhoY1ltNnJhcjd4WFh3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: stable
